"""Record a Python-side golden tape for the JavaScript engine.

For each seed: build two mock squads (Python mock.py), auto-pick both XIs,
then simulate a match while recording every rng.random() draw. The JS test
replays the tape through its own engine and must reproduce the scorecard
ball for ball and consume the tape exactly. Run from the repo root:

    python3 web/tools/make_golden.py > web/test/golden.json
"""
import json
import random
import sys

sys.path.insert(0, ".")
from cricket.mock import mock_fixture              # noqa: E402
from cricket.model import pick_xi                  # noqa: E402
from cricket.sim.intent import IntentPlan          # noqa: E402
from cricket.sim.match import simulate_match, Outcome  # noqa: E402
from cricket.tuning import BallTuning, InningsTuning   # noqa: E402


class Tape(random.Random):
    def __init__(self, seed):
        super().__init__(seed)
        self.tape = []

    def random(self):
        v = super().random()
        self.tape.append(v)
        return v


PLANS = {"balanced": IntentPlan.balanced, "textbook": IntentPlan.textbook, "adaptive": IntentPlan.adaptive}
CITIES = [("Cape Town", "Sydney"), ("Pretoria", "Sydney"), ("Pretoria", "Melbourne"), ("Durban", "Perth")]


def player_json(p, pid):
    return {"id": pid, "firstName": p.first_name, "surname": p.surname, "age": p.age,
            "role": p.role.name, "kind": p.bowl_kind.name,
            "attrs": {"power": p.attrs.power, "composure": p.attrs.composure,
                      "attack": p.attrs.attack, "control": p.attrs.control}}


def innings_json(inn, ids):
    return {
        "total": inn.total, "wickets": inn.wickets, "balls": inn.balls,
        "batters": [{"id": ids[id(b.player)], "runs": b.runs, "balls": b.balls, "out": b.out,
                     "dismissedById": ids[id(b.dismissed_by)] if b.dismissed_by else None,
                     "fours": b.fours, "sixes": b.sixes} for b in inn.batters],
        "bowlers": [{"id": ids[id(c.player)], "balls": c.balls, "runs": c.runs, "wickets": c.wickets, "dots": c.dots}
                    for c in inn.bowlers],
        "fall": [[f.wicket, f.score, f.ball] for f in inn.fall],
        "phaseRuns": list(inn.phase_runs),
    }


def main():
    cases = []
    for seed in range(1, 41):
        home_city, away_city = CITIES[seed % len(CITIES)]
        home, away = mock_fixture(seed, home_city, away_city)
        ids = {}
        squads = {}
        pid = 0
        for side, team in (("home", home), ("away", away)):
            squads[side] = []
            for p in team.squad:
                ids[id(p)] = pid
                squads[side].append(player_json(p, pid))
                pid += 1
        hxi, axi = pick_xi(home), pick_xi(away)
        plan_name = list(PLANS)[seed % 3]
        plan_a = PLANS[plan_name]()
        plan_b = PLANS[list(PLANS)[(seed + 1) % 3]]()
        rng = Tape(seed * 7919 + 1)
        m = simulate_match(hxi, axi, BallTuning(), InningsTuning(), rng, plan_a, plan_b)
        cases.append({
            "seed": seed, "homePlan": plan_name, "awayPlan": list(PLANS)[(seed + 1) % 3],
            "home": {"name": home.name, "city": home.city, "country": home.country, "squad": squads["home"]},
            "away": {"name": away.name, "city": away.city, "country": away.country, "squad": squads["away"]},
            "homeXI": {"order": [ids[id(p)] for p in hxi.batting_order], "bowlers": [ids[id(p)] for p in hxi.bowlers]},
            "awayXI": {"order": [ids[id(p)] for p in axi.batting_order], "bowlers": [ids[id(p)] for p in axi.bowlers]},
            "tape": rng.tape,
            "expected": {
                "homeBatsFirst": m.home_bats_first,
                "outcome": m.outcome.name, "marginRuns": m.margin_runs, "marginWickets": m.margin_wickets,
                "ballsRemaining": m.balls_remaining,
                "innings1": innings_json(m.innings1, ids), "innings2": innings_json(m.innings2, ids),
            },
        })
    json.dump({"note": "Generated by web/tools/make_golden.py from the Python sim. Do not edit by hand.",
               "cases": cases}, sys.stdout)


if __name__ == "__main__":
    main()
